details:
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: MAi_1_R1
  files:
  - /n/scratch2/jnh7/am_rnaseq/data/MAi_1_R1.fastq
  genome_build: mm10
  metadata:
    descrption: KO_1
    genotype: KO
    replicate: 1
    researcher_sampleid: D8-6
    sampleid: KO_1
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: MAi_2_R1
  files:
  - /n/scratch2/jnh7/am_rnaseq/data/MAi_2_R1.fastq
  genome_build: mm10
  metadata:
    descrption: KO_2
    genotype: KO
    replicate: 2
    researcher_sampleid: D8-27
    sampleid: KO_2
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: MAi_3_R1
  files:
  - /n/scratch2/jnh7/am_rnaseq/data/MAi_3_R1.fastq
  genome_build: mm10
  metadata:
    descrption: WT_1
    genotype: WT
    replicate: 1
    researcher_sampleid: D8-28
    sampleid: WT_1
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: MAi_4_R1
  files:
  - /n/scratch2/jnh7/am_rnaseq/data/MAi_4_R1.fastq
  genome_build: mm10
  metadata:
    descrption: WT_2
    genotype: WT
    replicate: 2
    researcher_sampleid: D8-29
    sampleid: WT_2
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: MAi_5_R1
  files:
  - /n/scratch2/jnh7/am_rnaseq/data/MAi_5_R1.fastq
  genome_build: mm10
  metadata:
    descrption: KO_3
    genotype: KO
    replicate: 3
    researcher_sampleid: D8-30
    sampleid: KO_3
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: MAi_6_R1
  files:
  - /n/scratch2/jnh7/am_rnaseq/data/MAi_6_R1.fastq
  genome_build: mm10
  metadata:
    descrption: WT_3
    genotype: WT
    replicate: 3
    researcher_sampleid: D8-31
    sampleid: WT_3
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: MAi_7_R1
  files:
  - /n/scratch2/jnh7/am_rnaseq/data/MAi_7_R1.fastq
  genome_build: mm10
  metadata:
    descrption: KO_4
    genotype: KO
    replicate: 4
    researcher_sampleid: D8-32
    sampleid: KO_4
- algorithm:
    adapters:
    - truseq
    - polya
    aligner: star
    quality_format: Standard
    strandedness: unstranded
    trim_reads: false
  analysis: RNA-seq
  description: MAi_8_R1
  files:
  - /n/scratch2/jnh7/am_rnaseq/data/MAi_8_R1.fastq
  genome_build: mm10
  metadata:
    descrption: WT_4
    genotype: WT
    replicate: 4
    researcher_sampleid: D8-33
    sampleid: WT_4
fc_date: '2017-04-14'
fc_name: bcbio
upload:
  dir: ../final
